# Generated by Django 3.1.2 on 2020-10-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortendURL',
            new_name='ShorteneddURL',
        ),
    ]
