# Generated by Django 3.1.2 on 2020-10-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_auto_20201022_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorteneddurl',
            name='key',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
