# Generated by Django 3.1.2 on 2020-12-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0004_auto_20201231_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorteneddurl',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
